/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Testingrev } from "./Testingrev";
export * as factories from "./factories";
export { Testingrev__factory } from "./factories/Testingrev__factory";
